### ISSUE TITLE
Strange, negative Ranks shown before matches are played.

### ISSUE THREAD

**Issue by cheer4ftc** [orange-alliance/TOA-DataSync#17]
Reminder about this, moving to DataSync repo issue.
https://github.com/orange-alliance/the-orange-alliance/issues/226

Looks like it's still happening, possibly also correlated with wrong team lists being updated too. e.g.,  Rankings at this event:
https://theorangealliance.org/events/1819-VA-QTVA6B

**Comment by Techno11** [comment]
See https://github.com/orange-alliance/TOA-DataSync/commit/e6be0d74d28d3cba284450e573d60b76bc7c2ded

**Comment by cheer4ftc** [comment]
Thanks. Is there a way to double check the teamlist in the DataSync too? I'm seeing events on TOA that have the same team listed twice, and events on TOA that have teams listed that don't play in any matches. This seems to be a scorekeeper app issue, where scorekeepers add teams but then later don't use them, but the teams still show up in the teamlist when the archive is exported. It would be great if the DataSync could clean the teamlist to have the teamlist (and rankings?) only show teams that actually appear in the matchlist.
Let me know if I should open a new issue for this.

**Comment by Techno11** [comment]
Sure.  I'll make it so that when the auto sync first starts, it purges and reuploads the teams list.

**Comment by cheer4ftc** [comment]
Great! Thanks!
So now, last question: I think this will prevent errors with teamlists in future events. Is there a way to correct teamlists that have problems that are already on TOA (besides having to manually correct things in the db)? Maybe once a week, run a script that regenerates db teamlists for all events based on matchlists, so any errors will get fixed?
Again, this is probably the wrong place for this discussion, but I don't know where this question should be asked. Thx.

**Comment by cheer4ftc** [comment]
Spectacular!  Thanks!  How often (and when) does the autosync run?

**Comment by Techno11** [comment]
I'm talking about the auto sync in the DataSync.  I don't know off of the top of my head at what interval the auto sync runs. I'll have to discuss with other about the team list rebuilding script.

**Comment by cheer4ftc** [comment]
OK. Thanks. It would probably be a good idea to have the entire db reupload once a week or so, so that problems from all sources get fixed without manual interventions (e.g., scorekeeper SW updates like reporting high scores in rankings, teamlist issues, etc.). I dunno if this is happening already or has been discussed.

**Comment by Techno11** [comment]
The EventParticipant list will now get purged and reuploaded when the match schedule is posted.
