### ISSUE TITLE
Sort event list alphabetically

### ISSUE THREAD

**Issue by jvens** [orange-alliance/TOA-DataSync#26]
When the event list has 60+ events it would be a lot easier to find the correct event if they were sorted alphabetically.

**Comment by afera15** [comment]
@jvens I like FRC Style.  In FMS they go by date for events, then after the event has passed, it will go to the bottom of the list.  The second sort is alphabetically after the date sort.
![image](https://user-images.githubusercontent.com/16884208/66008756-c5b0ea80-e485-11e9-8777-8c36bba2441a.png)

**Comment by jvens** [comment]
I can agree with chronological.  Right now it seems to just be whatever order the server responded back with.  Maybe including the date of that event along with the name in the drop-down as an extra check that it is the correct event?

**Comment by Techno11** [comment]
Yes, this is because of the async function. Rarely do the request returns at the same time, or in the correct order. This is simple to do with a sorting algorithm.
