### ISSUE TITLE
403 Error when logging in

### ISSUE THREAD

**Issue by jvens** [orange-alliance/TOA-DataSync#45]
I just tried logging into the https://upload.theorangealliance.org/setup.html website and it gives me an "invalid username/password" error when entering myTOA info.  I can log into myTOA with that password combo, and it works on the old DataSync tool.  It appears to be giving a 403 error which I have copied below.

`VM21:1 POST https://www.googleapis.com/identitytoolkit/v3/relyingparty/verifyPassword?key=<key> 403`

**Comment by ofekashery** [comment]
Thanks!! Fixed.
