### ISSUE TITLE
Which version to use this weekend?

### ISSUE THREAD

**Issue by jvens** [orange-alliance/TOA-DataSync#46]
For the 7 league meets we are running this weekend in Iowa should I use the new web-based DataSync tool or should I use the exe version from last week?  I am only at 1 event, and most of the other scorekeepers this weekend may not be the most successful at debugging issues if they come up.  So the real question is if the web-based version is robust enough yet or not, as well as if the old version still works or not.

**Comment by ofekashery** [comment]
The web-based version is stable.
It fixes some bugs from the previous version and we recommend using the web-based version.

**Comment by jvens** [comment]
OK, I have let the scorekeepers know about the change and that they should use the new web-based version.  Thanks @ofekashery!
