### ISSUE TITLE
Feature Request: Change Event Name/Meta Data

### ISSUE THREAD

**Issue by jvens** [orange-alliance/TOA-DataSync#48]
Some of our events were entered into the FIRST database incorrectly.  There were some League Meets that were given numbers, and then other league meets were added that are earlier sequentially shifting all the numbers (Alderaan Meet 1 in TOA Database is actually the second Alderaan meet for example).  Also, because some of the names changed some of the events ended up in the database twice (Kashyyyk_2019_11_9_Meet3 and Kashyyyk_11-9-2019_Meet2 are really the same event for example).

It would be nice if I had a way to clean this up either through the DS tool or through myTOA on the website.  I did send @nholo1332 the spreadsheet with all the events we are really running, but I am happy to fix it myself if you can give me the access to do so.

**Comment by ofekashery** [comment]
Hey @jvens, you can then change the details of the event through your myTOA account, in the Admin tab of each event.
I will try to keep your events up to date.
![image](https://user-images.githubusercontent.com/16443111/68426332-9726dd80-01b0-11ea-88dd-f8f8665ddf94.png)

**Comment by jvens** [comment]
I do not see an Admin Tab on the event page or account page.  Only Rankings, Matches, Teams, and Insights.

![image](https://user-images.githubusercontent.com/7074504/68427175-3d51f380-016f-11ea-8a38-97398268edc6.png)

I don't know if it is related, but the events don't actually show up in the list of Events in the myTOA account page, but if I go to events in that list I do see an Admin tab.  My guess is you are handling my permissions slightly differently because I have Region Access instead of explicit access to each event.

**Comment by ofekashery** [comment]
Does the star button appear to you?
![image](https://user-images.githubusercontent.com/16443111/68427520-f554c000-01b2-11ea-8060-eeb59dbbe28a.png)

**Comment by jvens** [comment]
yes it does

![image](https://user-images.githubusercontent.com/7074504/68428894-a71fcc80-0172-11ea-934a-77cf5cce295f.png)

**Comment by ofekashery** [comment]
Oops, fixed!

**Comment by jvens** [comment]
Much better.  Thanks!

**Comment by jvens** [comment]
So I now see the Admin tab, but can't actually make edits.  I am getting a 403 error:

`POST https://functions.theorangealliance.org/updateEvent 403`

Here is the Post Data:
```
[{"event_key":"1920-IA-L4","season_key":"1920","event_name":"Lothal Meet 1","start_date":"2019-10-19 00:00:00","end_date":"2019-10-19 00:00:00","venue":"Iowa City High Cafeteria","city":"Iowa City","state_prov":"IA","country":"USA","website":null,"league_key":null}]
```

I was attempting to change the city from `Iowas City` to `Iowa City`

**Comment by ofekashery** [comment]
Try it now @jvens

**Comment by jvens** [comment]
It says successful, but I am not actually seeing the change when I refresh the page.  

Maybe related, but I am getting a 403 when trying to access some server status in my console:
```
DevTools failed to parse SourceMap: https://theorangealliance.org/assets/js/popper.min.js.map
DevTools failed to parse SourceMap: https://theorangealliance.org/assets/js/bootstrap.js.map
functions.theorangea….org/serverStatus:1 GET https://functions.theorangealliance.org/serverStatus 403
main.100b865….js:1 ERROR Error: permission_denied at /eventAPIs/1920-IA-L4: Client doesn't have permission to access the desired data.
    at main.100b865….js:1
    at onComplete (main.100b865….js:1)
    at Object.onComplete (main.100b865….js:1)
    at main.100b865….js:1
    at e.onDataMessage_ (main.100b865….js:1)
    at t.onDataMessage_ (main.100b865….js:1)
    at t.onPrimaryMessageReceived_ (main.100b865….js:1)
    at t.onMessage (main.100b865….js:1)
    at t.appendFrame_ (main.100b865….js:1)
    at t.handleIncomingFrame (main.100b865….js:1)
[Deprecation] '-webkit-appearance: listbox' for elements other than listbox select is deprecated and will be removed in M79, around December 2019. See https://www.chromestatus.com/features/5070237827334144 for more details.
﻿```

**Comment by ofekashery** [comment]
It's probably the cache..

**Comment by jvens** [comment]
Only if it is a server side cache, I have my client cache disabled: 
![image](https://user-images.githubusercontent.com/7074504/68433907-519ced00-017d-11ea-87d8-ee86f7672559.png)

**Comment by jvens** [comment]
I am not sure what was holding onto the old value.  Maybe the service worker somehow?  Anyway, I completely deleted all the site data and unregistered the service worker, logged in again and now the city appears to have changed.
