### ISSUE TITLE
Scorekeeper Application Link Incorrect

### ISSUE THREAD

**Issue by messenger-sean** [orange-alliance/TOA-DataSync#49]
The link to download the scorekeeper application at https://upload.toa.events/ ("here" hyperlink) results in an Error 404 - Page Not Found.

The link used is:
* https://github.com/FIRST-Tech-Challenge/scorekeeper/releases/tag/v1.1.2

The link *should be*:
* https://github.com/FIRST-Tech-Challenge/scorekeeper/releases/tag/1.1.2

Notice there is no `v` in the version tag for release 1.1.2.

FTC seems to be inconsistent about its release tags. `v1.1.1` has the `v`, whereas `1.1.0` does not.

**Comment by jvens** [comment]
I can't replicate the issue with the 404 Error.  For me it redirects to https://upload.theorangealliance.org/setup.html.  It might be an issue with your DNS not being synced yet.  It can take 24 hours for DNS chances to propagate through the network.

![image](https://user-images.githubusercontent.com/7074504/68430220-48a81d80-0175-11ea-9846-255b3fcab204.png)

**Comment by jvens** [comment]
Disregard what I said.  I thought you were talking about the toa.events link, not the FTC Scorekeeper link.

**Comment by messenger-sean** [comment]
Correct. Apologies for the confusion. I'm talking about the hyperlink visible here:

![image](https://user-images.githubusercontent.com/4318057/68430582-501ff480-017e-11ea-83a7-a6afbd25da58.png)

**Comment by jvens** [comment]
Instead of calling out a version, would it be better to link to https://github.com/FIRST-Tech-Challenge/scorekeeper/releases/latest instead?

**Comment by messenger-sean** [comment]
Perhaps -- I think that's up to you. 

If you feel comfortable that TOA DataSync will always work with the `latest` release, then that should be fine.

I would be cautious about your handling of `v` for the tag though, as that seems inconsistent on their side.
