### ISSUE TITLE
Judges Award will Only Upload Winner

### ISSUE THREAD

**Issue by afera15** [orange-alliance/TOA-DataSync#53]
We had multiple teams listed for the Judges Award (2nd and 3rd Place) at Kingsford but only winner is displayed.

**Comment by ofekashery** [comment]
It seems you only picked one team.
![image](https://user-images.githubusercontent.com/16443111/68991271-a15a7300-0865-11ea-812a-cfa6bc635b99.png)

**Comment by ofekashery** [comment]
Fixed.
