### ISSUE TITLE
Failed to upload team list and rankings to TOA

### ISSUE THREAD

**Issue by jvens** [orange-alliance/TOA-DataSync#54]
At an event last night they used the DataSync to upload event data for https://theorangealliance.org/events/1920-IA-L71.  It looks like the match results made it up to TOA, but the team list and rankings did not.  I just tried again with the archive file and see the same issue.  

I generated logs and dropped the archive .db file into the zip folder attached.  In the webconsole I am seeing the following relevant errors:

```
Failed to load resource: the server responded with a status of 503 (Service Unavailable)
sync.bundle.js:344 Uploading rankings... 
Array(8)
theorangealliance.or…1920-IA-L71/teams:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
sync.bundle.js:344 TOA-ERROR Internal Server Error DELETE /event/1920-IA-L71/teams 
Object
theorangealliance.or…0-IA-L71/rankings:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
sync.bundle.js:344 TOA-ERROR Internal Server Error DELETE /event/1920-IA-L71/rankings 
Object
sync.bundle.js:337 Uncaught (in promise) Error: Request failed with status code 500
    at e.exports (sync.bundle.js:337)
    at e.exports (sync.bundle.js:344)
    at XMLHttpRequest.f.onreadystatechange (sync.bundle.js:337)
```

[1920-IA-L71 Logs.zip](https://github.com/orange-alliance/TOA-DataSync/files/3851952/1920-IA-L71.Logs.zip)

**Comment by ofekashery** [comment]
Thanks! Fixed in f8cae84.
We re-uploaded the data for this event.
