### ISSUE TITLE
Matches missing on 1920-IA-M41

### ISSUE THREAD

**Issue by jvens** [orange-alliance/TOA-DataSync#55]
Not sure exactly what is wrong, but TOA shows 13 matches but when you click on the matches tab no matches show up.  I just tried to re-sync the data using the DS tool and it says my access to that event has expired.  Can you please re-sync the data.

Also, what is the window on access time.  Not all of our events have internet connection and the ability to run DS live, and those events I sync when I receive the archive files usually a day or two after the event is over.  I had the same issue trying to sync an event from Thursday last week yesterday.

[mandalore_2019_10_19_meet1.zip](https://github.com/orange-alliance/TOA-DataSync/files/3860374/mandalore_2019_10_19_meet1.zip)

**Comment by Nate2019** [comment]
Fixed.

**Comment by ofekashery** [comment]
From now, the window on access time is 6 days before and 6 days after the event.
