### ISSUE TITLE
Purge not working

### ISSUE THREAD

**Issue by jvens** [orange-alliance/TOA-DataSync#58]
I noticed that one of our events (https://theorangealliance.org/events/1920-IA-L9) has incorrect data from a previous event in it.  I believe this probably happened when many of our events were named incorrectly.

I have attempted to purge the data from that event using the DS tool and get this error:

```
DELETE https://theorangealliance.org/api/event/1920-IA-L9/matches/all 500 (Internal Server Error)
sync.bundle.js:337 Uncaught (in promise) Error: Request failed with status code 500
    at e.exports (sync.bundle.js:337)
    at e.exports (sync.bundle.js:344)
    at XMLHttpRequest.f.onreadystatechange (sync.bundle.js:337)
```

Can you please delete the data from this event before Saturday?

**Comment by jvens** [comment]
Any update on this?  Right now it shows results and rankings from both events.  The correct archive file for this event is here.  Can you please purge the data and re-sync it?

[lothal_2019_12_14_meet8.zip](https://github.com/orange-alliance/TOA-DataSync/files/3974436/lothal_2019_12_14_meet8.zip)

**Comment by ofekashery** [comment]
We fixed the purge button and re-sync it.

**Comment by jvens** [comment]
Perfect, thanks @ofekashery!
